AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Mappings:
  Database:
    Name:
      Value: SocialMediaMasterDB
    Username:
      Value: socialmediauser
    Password:
      Value: socialmediapass
    Identifier:
      Value: socialmediadb
Resources:
  SocialMediaMasterDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier:
        Fn::FindInMap:
        - Database
        - Identifier
        - Value
      DBName:
        Fn::FindInMap:
        - Database
        - Name
        - Value
      Engine: postgres
      MasterUsername:
        Fn::FindInMap:
        - Database
        - Username
        - Value
      MasterUserPassword:
        Fn::FindInMap:
        - Database
        - Password
        - Value
    DeletionPolicy: Snapshot
    Metadata:
      SamResourceId: SocialMediaMasterDB
  SocialMediaAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: '''*'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
      Auth:
        DefaultAuthorizer: SocialMediaCognitoUserPoolAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          SocialMediaCognitoUserPoolAuthorizer:
            UserPoolArn:
              Fn::GetAtt:
              - SocialMediaCognitoUserPool
              - Arn
    Metadata:
      SamResourceId: SocialMediaAPI
  SocialMediaCore:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      Runtime: nodejs10.x
      CodeUri: s3://cf-templates-1j38krxlf5m0l-eu-west-1/741acc9794fa836ad428159cd4ee8431
      Policies:
      - AmazonS3FullAccess
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST:
            Fn::GetAtt:
            - SocialMediaMasterDB
            - Endpoint.Address
          DB_NAME:
            Fn::FindInMap:
            - Database
            - Name
            - Value
          DB_USER:
            Fn::FindInMap:
            - Database
            - Username
            - Value
          DB_PASS:
            Fn::FindInMap:
            - Database
            - Password
            - Value
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: SocialMediaAPI
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId:
              Ref: SocialMediaAPI
            Path: /{proxy+}
            Method: ANY
    Metadata:
      SamResourceId: SocialMediaCore
  SocialMediaCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: sam_api_gateway_cup_auth_cognito_user_pool
      LambdaConfig:
        PreSignUp:
          Fn::GetAtt:
          - PreSignupLambdaFunction
          - Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
      - email
      Schema:
      - AttributeDataType: String
        Name: email
        Required: false
    Metadata:
      SamResourceId: SocialMediaCognitoUserPool
  SocialMediaCognitoUserDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain:
        Ref: SocialMediaAPI
      UserPoolId:
        Ref: SocialMediaCognitoUserPool
    Metadata:
      SamResourceId: SocialMediaCognitoUserDomain
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: sam_api_gateway_cup_auth_cognito_client
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
      - code
      - implicit
      AllowedOAuthScopes:
      - email
      - openid
      CallbackURLs:
      - https://social-media-app-hosting-bucket.s3-eu-west-1.amazonaws.com/index.html
      LogoutURLs:
      - https://social-media-app-hosting-bucket.s3-eu-west-1.amazonaws.com/index.html
      SupportedIdentityProviders:
      - COGNITO
      UserPoolId:
        Ref: SocialMediaCognitoUserPool
    Metadata:
      SamResourceId: CognitoUserPoolClient
  PreSignupLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: "exports.handler = async (event, context, callback) => {\n  event.response\
        \ = { autoConfirmUser: true }\n  return event\n}\n"
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs10.x
      Timeout: 3
    Metadata:
      SamResourceId: PreSignupLambdaFunction
  LambdaCognitoUserPoolExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - PreSignupLambdaFunction
        - Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn:
        Fn::Sub: arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${SocialMediaCognitoUserPool}
    Metadata:
      SamResourceId: LambdaCognitoUserPoolExecutionPermission
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketName: social-media-app-hosting-bucket
    DeletionPolicy: Retain
    Metadata:
      SamResourceId: S3Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3Bucket
              - /*
      Bucket:
        Ref: S3Bucket
    Metadata:
      SamResourceId: BucketPolicy
  MainS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: social-media-app-main-bucket
    DeletionPolicy: Retain
    Metadata:
      SamResourceId: MainS3Bucket
  MainBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MainMyPolicy
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: MainS3Bucket
              - /*
      Bucket:
        Ref: MainS3Bucket
    Metadata:
      SamResourceId: MainBucketPolicy
Outputs:
  Region:
    Description: Region
    Value:
      Ref: AWS::Region
  ApiId:
    Description: API ID
    Value:
      Ref: SocialMediaAPI
  ApiUrl:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${SocialMediaAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/
  CognitoUserPoolId:
    Description: Cognito User Pool Id
    Value:
      Ref: SocialMediaCognitoUserPool
  CognitoUserPoolClientId:
    Description: Cognito User Pool Client Id
    Value:
      Ref: CognitoUserPoolClient
  WebsiteURL:
    Value:
      Fn::GetAtt:
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Fn::GetAtt:
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
